### ISSUE TITLE
No need for let?!

### ISSUE THREAD

**Issue by zartstrom** [lwm/haskellbook-berlin#2]
Apparently this works:

```
~ » ghci
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
Prelude> x = 5
Prelude> x * 3
15
Prelude>
```

There is no need to write `let x = 5` (with let)?

**Comment by lwm** [comment]
Yes @zartstrom, you are correct!

Didn't know that one either. Just upgraded my `ghci` now.

Rooting through the [GHCs 8.0.1 release notes][1], I got the right ticket, [Top-level bindings in ghci][2]!

Huzzah :)


[1]: https://downloads.haskell.org/~ghc/master/users-guide/8.0.1-notes.html#ghci
[2]: https://ghc.haskell.org/trac/ghc/ticket/7253

**Comment by zartstrom** [comment]
it's a _new_ feature :+1:  Hadn't thought of that ;) thanks
