### ISSUE TITLE
What is `term-level`?

### ISSUE THREAD

**Issue by lwm** [lwm/haskellbook-berlin#5]
I keep seeing it everywhere and it isn't making sense? An example?

**Comment by mheinzel** [comment]
Term-level means on the level of terms/values (as opposed to on the level of types). 
```haskell
foo :: Int -> a -> Maybe a                   -- type level
foo n a = if n > 0 then Just a else Nothing  -- term level
```
Those are two different levels, which should not be confused with each other. The ```a``` in the first line stands for an anonymous **type**, on the second line it is the name of the argument and refers to a **value**.

**Comment by lwm** [comment]
Thanks @mheinzel! I normally read 'value level', so it was confusing. All clear now!
