### ISSUE TITLE
integral division with negative numbers

### ISSUE THREAD

**Issue by thought2** [lwm/haskellbook-berlin#7]
dear haskellers,

I'm referring here to chapter 8, section "Fixing dividedBy" (page 493, e-reader version)

It's about a re-implementation of divMod basically. The division should be implemented just by using successive substractions. And in contrast to Prelude's divMod it should handle division by zero with a special data type. I think the following code does this so far. However it does not work for negative values. Anybody ideas how to fix this?

```
data DivResult a =
    Result (a, a)
  | DivByZero deriving Show

divMod' :: Integral a => a -> a -> DivResult a
divMod' num denum = go num denum 0
  where go n d i
         | d == 0 = DivByZero
         | n < d  = Result (i, n)
         | True   = go (n-d) d (i+1)

```

**Comment by mheinzel** [comment]
A bit late and there might be a better way, but here is what I came up with.

1. **Negative denominators**:
  You can handle them using the following equalities:
  `div a b = div (-a) (-b)`
  `mod a b = - mod (-a) (-b)`
  So, every `divMod` with a negative denominator can be calculated using a positive denominator.

2. **Negative numerators**:
  What you are currently doing in `go` is bringing `n` in the `[0 .. d-1]` range. Then, you have your solution: The remaining `n` is your `mod`, the number of steps to get there is your `div`.

  So you already have:
  - If `n >= d`, keep subtracting `d` from it.

  To handle negative `n`, you need the opposite as well:
  - If `n < 0`, keep adding `d`.


The solution could look like this:
```haskell
divMod' num denom
    | denom > 0  = go num denom 0
    | denom < 0  = let Result (dv, md) = go (-num) (-denom) 0
                   in Result (dv, -md) -- negative denominator
    | otherwise  = DivByZero
  where
    go n d i
        | n <  0    = go (n+d) d (i-1) -- negative numerator
        | n >= d    = go (n-d) d (i+1)
        | otherwise = Result (i, n)
```
